config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root   'blogs#index'
  resources :blogs
  get    'users/:id'       => 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @blogs = Blog.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
    @blog = Blog.new
  end

  def create
    Blog.create(text: blog_params[:text], user_id: current_user.id)
  end

  def destroy
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.destroy
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.update(blog_params)
    end
  end

  private
  def blog_params
    params.permit(:text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @nickname = current_user.nickname
    @blogs = current_user.blogs.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
<%= simple_format(blog.text) %>
<span class="name">
  <a href="">
    <span>投稿者</span><%= blog.user.nickname %>
  </a>

  <% if user_signed_in? && current_user.id == blog.user_id %>
    <div class="more">
      <ul class="more_list">
        <div style="display:inline-flex">
          <li>
            <%= link_to '編集', edit_blog_path(blog), class: "waves-effect waves-light btn" %>
          </li>
          <li>
            <%= link_to '削除', blog_path(blog), class: "waves-effect waves-light btn", :method => :delete %>
          </li>
        </div>
      </ul>
    </div>
  <% end %>

</span>

app/views/blogs/create.html.erb
<div class="contents row">
  <div class="success">
    <h5>
      投稿が完了しました。
    </h5>
    <a class="btn" href="/blogs">投稿一覧へ戻る</a>
  </div>
</div>

app/views/blogs/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h5>
      削除が完了しました。
    </h5>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="contents row">
  <%= form_for @blog do |form|%>
    <h5>
      編集する
    </h5>

    <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, placeholder: "本文", name: "text" %>
    </div>

    <div class="actions">
    <%= form.submit "送信" %>
    </div>

  <% end %>
</div>

app/views/blogs/index.html.erb
<div class="container">
<div class="contents center row" >
  <% @blogs.each do |blog| %>
    <div class="row">
      <div class="col s12 m12">
        <div class="card white">
          <div class="card-content black-text">
            <span class="card-title"></span>
              <p><%= render partial: "blog", locals: { blog: blog } %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate(@blogs) %>
</div>
</div>

app/views/blogs/new.html.erb
<div class="contents row">
  <%= form_for @blog do |form| %>
    <h4>
      投稿する
    </h4>

    <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, placeholder: "本文", name: "text" %>
    </div>

    <div class="actions">
    <%= form.submit "送信" %>
    </div>

  <% end %>
</div>

app/views/blogs/update.html.erb
  <div class="success">
    <h5>
      更新が完了しました。
    </h5>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miniblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style type="text/css" href="./style.css"></style>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

    <script
    src="https://code.jquery.com/jquery-3.3.1.js"
    integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
  </head>

  <body>

  <nav>
    <header>
      <div class="nav-wrapper">
        <a href="/blogs" class="brand-logo center">Blog</a>
        <ul id="nav-mobile">
          <% if user_signed_in? %>
            <li><a href="/users/<%= current_user.id %>"><%= current_user.nickname %></a></li>
            <li><a href="/blogs/new">投稿する</a></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <div class="grid-6">
              <%= link_to "ログイン", new_user_session_path, class: 'post' %>
              <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
            </div>
          <% end %>
        </ul>
      </div>
    </header>
  </nav>

  <script type="text/javascript" src="./app.js"></script>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="container">
<div class="contents center row" >
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @blogs.each do |blog| %>
    <div class="row">
      <div class="col s12 m12">
        <div class="card white">
          <div class="card-content black-text">
            <span class="card-title"></span>

              <p><%= render partial: "blogs/blog", locals: { blog: blog } %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate(@blogs) %>
</div>
</div>